import kotlin.io.path.Path

class AwsConfig(customPath: String? = null) {
    val path = Path(customPath ?: defaultAWSConfigPath())

    fun toConfig(): Config {
        val awsConfig = path.toFile().readText()
        val profiles = parseIni(awsConfig).map { (name, properties) ->
            Profile.fromSection(name, properties)
        }
        return Config(profiles)
    }

    fun write(profile: Profile) {
        FileHelpers.backup(path)
        path.toFile().writeText(
            """
            # Autogenerated by AWSetup

            [default]
            aws_access_key_id=${profile.key.unmask()}
            aws_secret_access_key=${profile.secret.unmask()}
        """.trimIndent()
        )
    }
}

private fun defaultAWSConfigPath(): String {
    return Path(getHomePath(), ".aws/credentials").toString()
}
